<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="Server">
    
    <hr/><hr/><hr/>
    <asp:AccessDataSource ID="AccesDataSource" runat="server" DataFile="~/App_Data/Printer.mdb" SelectCommand="SELECT * FROM printers" DeleteCommand="DELETE FROM printers WHERE ID=?">
        <DeleteParameters>
            <asp:ControlParameter ControlID="GridView1" Name="ID" PropertyName="SelectedValue" />
        </DeleteParameters>
    </asp:AccessDataSource>
    <asp:GridView ID="GridView1" DataSourceID="AccesDataSource" runat="server" AllowPaging="True" AllowSorting="True" BorderStyle="Groove" CellPadding="-1" CellSpacing="10" CssClass="table" AllowCustomPaging="False" AutoGenerateDeleteButton="True" DataKeyNames="ID">
    </asp:GridView>
    

    <%--<div class="row">
        <div class="col-md-2">
            <% foreach (var printer in Printers)
               {
                %>
                <p>Model : <% printer.Model.ToString(); %></p>
                <p>Type : <% printer.Type.ToString(); %></p>
                <p>Material : <% printer.Material.ToString(); %></p>
                <p>Location : <% printer.Location.ToString(); %></p>
                <p>Mark : <% printer.Mark.ToString(); %></p>
                <p>Fucntion : <% printer.Function.ToString(); %></p>
                <p>Paper : <% printer.Paper.ToString(); %></p>
                <% } %>
        </div>
    </div>--%>
    <%--<div class="jumbotron">
        <h1>ULOGIRANI STEEEEEEEEEEEEEEEEEEEEEEE</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.</p>
        <p><a href="http://www.asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET Web Forms lets you build dynamic websites using a familiar drag-and-drop, event-driven model.
            A design surface and hundreds of controls and components let you rapidly build sophisticated, powerful UI-driven sites with data access.
            </p>
            <p>
                <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301948">Learn more &raquo;</a>
            </p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>
                NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.
            </p>
            <p>
                <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301949">Learn more &raquo;</a>
            </p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>
                You can easily find a web hosting company that offers the right mix of features and price for your applications.
            </p>
            <p>
                <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301950">Learn more &raquo;</a>
            </p>
        </div>
    </div>--%>
</asp:Content>

