<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Storage.aspx.cs" Inherits="Storage" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" Runat="Server">
    <hr/><hr/><hr/>
    <asp:AccessDataSource ID="AccesDataSource" runat="server" DataFile="~/App_Data/Printer.mdb" SelectCommand="SELECT * FROM storage" DeleteCommand="DELETE FROM storage WHERE ID=?">
        <DeleteParameters>
            <asp:ControlParameter ControlID="GridView1" Name="ID" PropertyName="SelectedValue" />
        </DeleteParameters>
    </asp:AccessDataSource>
    <asp:GridView ID="GridView1" DataSourceID="AccesDataSource" runat="server" AllowPaging="True" AllowSorting="True" BorderStyle="Groove" CellPadding="-1" CellSpacing="10" CssClass="table" AllowCustomPaging="False" AutoGenerateDeleteButton="True" DataKeyNames="ID">
    </asp:GridView>
</asp:Content>

