<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Tablica.aspx.cs" Inherits="Tablica" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>About Me</title>
    <link rel="stylesheet" type="text/css" href="Style.css" />
</head>
<body>
    <form id="form1" runat="server">
        <div id="body">

            <asp:AccessDataSource ID="AccessDataSource1"
                runat="server"
                DataFile="/App_Data/ASP_Database.mdb"
                SelectCommand="SELECT * FROM studenti"
                DeleteCommand=""
                UpdateCommand=""
                >
            </asp:AccessDataSource>
            <asp:GridView runat="server"
                DataSourceID="AccessDataSource1" 
                AllowPaging="True"
                AutoGenerateDeleteButton="True" 
                AutoGenerateSelectButton="True"
                CellPadding="3"
                AllowSorting="True" 
                BackColor="White" 
                BorderColor="#CCCCCC"
                BorderStyle="None" 
                BorderWidth="1px" 
                DataKeyNames="ID" 
                CssClass="tablica"
                >
                <FooterStyle BackColor="White" ForeColor="#000066" />
                <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                <RowStyle ForeColor="#000066" />
                <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#007DBB" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#00547E" />
            </asp:GridView>
            <asp:LoginStatus ID="LoginStatus1" runat="server" LoginText="Log In" LogoutText="Log Out" />

            <br />
            <asp:LoginName ID="LoginName2" runat="server" />

            <br />
            <br />
        </div>
    </form>
</body>
</html>
