<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Tablica.aspx.cs" Inherits="Tablica" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Tablica</title>
    <link rel="stylesheet" type="text/css" href="Style.css" />
</head>
<body>
    <form id="form1" runat="server">
        <div id="body">

            <asp:AccessDataSource ID="AccessDataSource1"
                runat="server"
                DataFile="/App_Data/ASP_Database.mdb"
                SelectCommand="SELECT * FROM studenti" DeleteCommand="DELETE FROM studenti WHERE ID=? " UpdateCommand="UPDATE studenti SET JMBAG=?, Ime=?, Prezime=?, Grupa=?, Kontakt=? WHERE ID=?" InsertCommand="INSERT INTO [studenti] ([ID], [JMBAG], [Ime], [Prezime], [Kontakt]) VALUES (?, ?, ?, ?, ?, ?)">
                <DeleteParameters>
                    <asp:ControlParameter ControlID="GridView1" Name="ID" PropertyName="SelectedValue" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="ID" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="JMBAG" Type="Double"></asp:Parameter>
                    <asp:Parameter Name="Ime" Type="String"></asp:Parameter>
                    <asp:Parameter Name="Prezime" Type="String"></asp:Parameter>
                    <asp:Parameter Name="Grupa" Type="String"></asp:Parameter>
                    <asp:Parameter Name="Kontakt" Type="String"></asp:Parameter>
                </InsertParameters>
                <UpdateParameters>
                    <asp:ControlParameter ControlID="GridView1" Name="JMBAG" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="Ime" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="Prezime" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="Grupa" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="Kontakt" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="ID" PropertyName="SelectedValue" />
                </UpdateParameters>
            </asp:AccessDataSource>
            <asp:GridView runat="server"
                ID="GridView1"
                DataSourceID="AccessDataSource1"
                AllowPaging="True"
                AutoGenerateDeleteButton="True"
                AutoGenerateSelectButton="True"
                CellPadding="3"
                AllowSorting="True"
                BackColor="White"
                BorderColor="#CCCCCC"
                BorderStyle="None"
                BorderWidth="1px"
                DataKeyNames="ID"
                AutoGenerateEditButton="True">
                <FooterStyle BackColor="White" ForeColor="#000066" />
                <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                <RowStyle ForeColor="#000066" />
                <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#007DBB" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#00547E" />
            </asp:GridView>
            <asp:LoginStatus ID="LoginStatus1" runat="server" LoginText="Log In" LogoutText="Log Out" />

            <br />

            <div id="content">
                <div  >Ime: </div>
                <asp:TextBox runat="server" ID="ImeUnos" CssClass="UnosStudenta"></asp:TextBox>
                <br />
                <div  >Prezime: </div>
                <asp:TextBox runat="server" ID="PrezimeUnos"></asp:TextBox>
                <br />
                <div  >JMBAG: </div>
                <asp:TextBox runat="server" ID="JmbagUnos"></asp:TextBox>
                <br />
                <div  >Grupa:</div>
                <asp:TextBox runat="server" ID="GrupaUnos"></asp:TextBox>
                <br />
                <div  >Kontakt:</div>
                <asp:TextBox runat="server" ID="KontaktUnos"></asp:TextBox>
                <br />
                <asp:Button runat="server"
                    ID="SubmitUnos"
                    Text="Confirm"
                    OnClick="Submit_Click" />
            </div>
            
            <br />
            <br />

            <div id="regForm">
                <div  >Trazi ime: </div>
                <asp:TextBox runat="server" ID="TraziIme"></asp:TextBox>
                <div  >Trazi prezime: </div>
                <asp:TextBox runat="server" ID="TraziPrezime"></asp:TextBox>
                <asp:Button runat="server" ID="SubmitTrazi" Text="Trazi"
                    OnClick="SubmitTrazi_Click" />

            </div>

            <br />
            <asp:LoginName ID="LoginName2" runat="server" />

            <br />
            <br />
        </div>
    </form>
</body>
</html>
